library(dplyr)
library(ggplot2)
library(tidyr)
library(shiny)
library(plotly)
library(maps)
library(rsconnect)
library(scales)
library(mapproj)
options(scipen = 999)

source("my_ui.R")
source("my_server.R")

shinyApp(ui = my_ui, server = my_server)
